-- FINAL PROJECT

-- DROP DATABASE 
DROP DATABASE FINAL;

-- CREATE DATABASE
CREATE DATABASE FINAL;

-- USE DATABASE
USE FINAL;

-- CREATING TABLE
CREATE TABLE STUDENTS (
    STUDENTID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    BIRTHDATE DATE,
    ENROLLMENTDATE DATE
);

CREATE TABLE DEPARTMENTS (
    DEPARTMENTID INT PRIMARY KEY,
    DEPARTMENTNAME VARCHAR(100)
);

CREATE TABLE COURSES (
    COURSEID INT PRIMARY KEY,
    COURSENAME VARCHAR(100),
    DEPARTMENTID INT,
    CREDITS INT,
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS(DEPARTMENTID)
);

CREATE TABLE INSTRUCTORS (
    INSTRUCTORID INT PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    DEPARTMENTID INT,
    FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENTS(DEPARTMENTID)
);

CREATE TABLE ENROLLMENTS (
    ENROLLMENTID INT PRIMARY KEY,
    STUDENTID INT,
    COURSEID INT,
    ENROLLMENTDATE DATE,
    FOREIGN KEY (STUDENTID) REFERENCES STUDENTS(STUDENTID),
    FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID)
);

-- INSERTING RECORDS
INSERT INTO STUDENTS VALUES
(1, 'JOHN', 'DOE', 'JOHN.DOE@EMAIL.COM', '2000-01-15', '2022-08-01'),
(2, 'JANE', 'SMITH', 'JANE.SMITH@EMAIL.COM', '1999-05-25', '2021-08-01');

INSERT INTO DEPARTMENTS VALUES
(1, 'COMPUTER SCIENCE'),
(2, 'MATHEMATICS');

INSERT INTO COURSES VALUES
(101, 'INTRODUCTION TO SQL', 1, 3),
(102, 'DATA STRUCTURES', 2, 4);

INSERT INTO INSTRUCTORS VALUES
(1, 'ALICE', 'JOHNSON', 'ALICE.JOHNSON@UNIV.COM', 1),
(2, 'BOB', 'LEE', 'BOB.LEE@UNIV.COM', 2);

INSERT INTO ENROLLMENTS VALUES
(1, 1, 101, '2022-08-01'),
(2, 2, 102, '2021-08-01');

-- 1. CRUD OPERATIONS
-- INSERT
INSERT INTO STUDENTS VALUES (3, 'MIRA', 'PATEL', 'MIRA@GMAIL.COM', '2001-12-05', '2023-08-01');

-- UPDATE
UPDATE STUDENTS SET EMAIL='JOHN.NEW@EMAIL.COM' WHERE STUDENTID=1;

-- DELETE
DELETE FROM STUDENTS WHERE STUDENTID=3;

-- READ
SELECT * FROM STUDENTS;

-- 2. RETRIEVE STUDENTS WHO ENROLLED AFTER 2022
SELECT * FROM STUDENTS
WHERE YEAR(ENROLLMENTDATE) > 2022;

-- 3. COURSES OFFERED BY MATHEMATICS WITH LIMIT 5
SELECT * FROM COURSES
WHERE DEPARTMENTID = 1
LIMIT 5;

-- 4. NUMBER OF STUDENTS ENROLLED IN EACH COURSE (MORE THAN 5 FILTER)
SELECT COURSEID, COUNT(STUDENTID) AS TOTALSTUDENTS
FROM ENROLLMENTS
GROUP BY COURSEID
HAVING COUNT(STUDENTID) > 5;

-- 5. STUDENTS ENROLLED IN BOTH SQL & DATA STRUCTURES
SELECT S.STUDENTID, S.FIRSTNAME, S.LASTNAME
FROM STUDENTS S
WHERE S.STUDENTID IN (
    SELECT STUDENTID FROM ENROLLMENTS WHERE COURSEID = 103
)
AND S.STUDENTID IN (
    SELECT STUDENTID FROM ENROLLMENTS WHERE COURSEID = 104
);

-- 6. EITHER STUDENTS ENROLLED IN SQL OR DATA STRUCTURES
SELECT DISTINCT S.STUDENTID, S.FIRSTNAME, S.LASTNAME
FROM STUDENTS S
JOIN ENROLLMENTS E ON S.STUDENTID = E.STUDENTID
WHERE E.COURSEID IN (101, 102);

-- 7. AVERAGE NUMBER OF CREDITS
SELECT AVG(CREDITS) AS AVGCREDITS FROM COURSES;

-- 9. COUNT STUDENTS IN EACH DEPARTMENT
SELECT D.DEPARTMENTNAME, COUNT(E.STUDENTID) AS TOTALSTUDENTS
FROM DEPARTMENTS D
LEFT JOIN COURSES C ON D.DEPARTMENTID = C.DEPARTMENTID
LEFT JOIN ENROLLMENTS E ON C.COURSEID = E.COURSEID
GROUP BY D.DEPARTMENTNAME;

-- 10. INNER JOIN - STUDENTS & THEIR COURSES
SELECT S.FIRSTNAME, S.LASTNAME, C.COURSENAME
FROM STUDENTS S
INNER JOIN ENROLLMENTS E ON S.STUDENTID = E.STUDENTID
INNER JOIN COURSES C ON E.COURSEID = C.COURSEID;

-- 11. LEFT JOIN - ALL STUDENTS AND THEIR COURSES
SELECT S.FIRSTNAME, S.LASTNAME, C.COURSENAME
FROM STUDENTS S
LEFT JOIN ENROLLMENTS E ON S.STUDENTID = E.STUDENTID
LEFT JOIN COURSES C ON E.COURSEID = C.COURSEID;

-- 12. SUBQUERY - COURSES WITH > 10 STUDENTS
SELECT STUDENTID, COURSEID
FROM ENROLLMENTS
WHERE COURSEID IN (
    SELECT COURSEID
    FROM ENROLLMENTS
    GROUP BY COURSEID
    HAVING COUNT(STUDENTID) > 10
);

-- 13. EXTRACT YEAR FROM ENROLLMENTDATE
SELECT STUDENTID, YEAR(ENROLLMENTDATE) AS ENROLLYEAR
FROM STUDENTS;

-- 14. CONCATENATE INSTRUCTOR FULL NAME
SELECT CONCAT(FIRSTNAME, ' ', LASTNAME) AS FULLNAME
FROM INSTRUCTORS;

-- 15. RUNNING TOTAL OF STUDENTS ENROLLED
SELECT ENROLLMENTID, STUDENTID,
       SUM(1) OVER (ORDER BY ENROLLMENTID) AS RUNNINGTOTAL
FROM ENROLLMENTS;

-- 16. LABEL SENIOR / JUNIOR
SELECT STUDENTID, FIRSTNAME, ENROLLMENTDATE,
CASE 
    WHEN YEAR(CURDATE()) - YEAR(ENROLLMENTDATE) > 2
        THEN 'SENIOR'
    ELSE 'JUNIOR'
END AS STUDENTLEVEL
FROM STUDENTS;
